### ISSUE TITLE
it doesnt work from the box!

### ISSUE THREAD

**Issue by ChepelDrepel** [fireflyprotocol/firefly-client-python#49]
1. `pip install "python-socketio[client]"` u should note this in installation section, not so obvious to fix, and socket doesnt work without it 
[socketio docs link](https://python-socketio.readthedocs.io/en/latest/client.html#installation)
2. in firefly_exchange_client.py line 634 get_contract_addresses is a sync function, but defined as async 
3. `FireflyClient.__init__()`
`self.contracts.contract_addresses = async.run(self.get_contract_addresses())` wtf is this?
seems like nobody even tried to run it before publish
4. most probably all ur async functions which uses `self.apis.get()` are not async at all

**and please, document ur api!**

**Comment by Ahmadjawaid** [comment]
Hey @ChepelDrepel - the latest release should resolve the aforementioned points https://github.com/fireflyprotocol/firefly-client-python/releases/tag/v0.1.1. Additionally, the documentation for the API can be found linked in the ReadMe, but here's a direct link: docs.bluefin.io.

Appreciate the candid feedback - keep it coming 😉
